# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b3c7cbc6c79ae53ff3fd798fe434a53e"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "Dealclub Bestellungen"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_orders,read_orders"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
